#!/usr/bin/env bash
# configure the container to run nginx under nginx user on port 8080
sed -i "s/80 /8080 /g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
chmod 755 /etc/nginx/nginx.conf
pkill -9 apache
su nginx -c "service nginx restart"
